### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by glarrain** [denied/denied#2]
Is this project alive? RIP? Just taking a break? Hosted somewhere else?

**Comment by kennethreitz** [comment]
May the dream never die.

**Comment by bastianh** [comment]
This project is already perfect. There is nothing that could be improved.

If you look for a similar project with a larger userbase you might want to check out http://flask.pocoo.org/.

**Comment by glarrain** [comment]
Well, some might find it works very good, but it's quite far from perfect. For instance, there is no documentation, no docstrings, comments, anything. IMO no software can be considered perfect at any time.

**Comment by kennethreitz** [comment]
@glarrain: denied was an april fool's joke. However, the attention it got led Armin to make flask:
http://flask.pocoo.org/

**Comment by glarrain** [comment]
Haha it all makes sense now. Thanks for the heads up.
